# Bases de datos en Python

<a id="sql"></a>
## Acceso a bases de datos relacionales

Podemos acceder a bases de datos SQL con la librería `pymysql`. Para instalarla escribimos en Anaconda Prompt:  
`conda install -c anaconda pymysql`

#### Ejemplo 1
Vamos a conectarnos a la base de datos NBA, que contiene estadísticas de partidos de una temporada.  
Utilizaremos los siguientes parámetros:  
* servidor: relational.fit.cvut.cz
* usuario: guest
* contraseña: relational  
* base de datos: NBA

<img src="https://relational.fit.cvut.cz/assets/img/datasets-generated/NBA.svg" width="400">  

Vamos a crear una conexión con la base de datos

In [34]:
data_base_host = 'relational.fit.cvut.cz'
username = 'guest'
password = 'relational'
database_name = 'NBA'

# conexión con la base de datos
db = pymysql.connect( host = data_base_host, user = username, password=  password, database = database_name )

# abrimos el archivo
cursor = db.cursor()

La función `connect()` crea una conexión a la base de datos. Un *cursor* nos permite realizar operaciones con los datos almacenados en la base de datos. Al ejecutar `cursor()` es como si estuviésemos utilizando `open()` cuando trabajábamos con archivos.  

<img src='https://i.ibb.co/L8HH0G5/cursor.png'>  

Una vez creado el cursor, podemos empezar a ejecutar comandos sobre el contenido de la base de datos utilizando el métido `execute()`,

Al ejecutar queries, utilizamos los métodos `fetchone()` (primera fila) o `fectchall()` (todas las filas) para visizar los resultados de las consultas. Para cerrar la conexión, utilizamso el método `close()`

In [15]:
cursor.execute(' SELECT * FROM Player ')
cursor.fetchone()

(1, 'Nicolas Batum')

Podemos ver las tablas de la base de datos con la query `SHOW TABLES`

In [18]:
cursor.execute('SHOW TABLES')
cursor.fetchall()

(('Actions',),
 ('Game',),
 ('Player',),
 ('Team',),
 ('joined_drafted_all_players_original',))

In [20]:
cursor.close()

El método `read_sql()` de pandas nos permite crear dataframes a partir de queries. Con este método no es necesario crear un cursor

In [26]:
import pandas as pd

In [36]:
query = 'SELECT * FROM Actions'
df = pd.read_sql(query, db)
df

/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,GameId,TeamId,PlayerId,Minutes,FieldGoalsMade,FieldGoalAttempts,3PointsMade,3PointAttempts,FreeThrowsMade,FreeThrowAttempts,...,DefensiveRebounds,TotalRebounds,Assists,PersonalFouls,Steals,Turnovers,BlockedShots,BlocksAgainst,Points,Starter
0,1,7,78,2605,5,14,3,3,0,0,...,3,3,4,2,1,1,0,0,13,1
1,1,7,79,2359,11,19,3,3,8,8,...,8,8,3,2,3,3,1,0,34,1
2,1,7,80,2104,6,7,3,3,3,8,...,7,9,1,3,1,1,2,0,15,1
3,1,7,81,1392,1,5,3,3,0,0,...,2,2,0,4,1,0,0,0,2,1
4,1,7,82,2124,5,8,3,3,1,2,...,3,3,6,1,1,4,0,0,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,30,25,316,0,0,0,3,3,0,0,...,0,0,0,0,0,0,0,0,0,0
763,30,25,317,0,0,0,3,3,0,0,...,0,0,0,0,0,0,0,0,0,0
764,30,25,318,0,0,0,3,3,0,0,...,0,0,0,0,0,0,0,0,0,0
765,30,17,344,0,0,0,3,3,0,0,...,0,0,0,0,0,0,0,0,0,0
766,30,17,390,0,0,0,3,3,0,0,...,0,0,0,0,0,0,0,0,0,0

Obtenemos los jugadores con más de 5 asistencias en algún partido

In [45]:
query = '''SELECT  PlayerName,Assists
         FROM Actions
         JOIN Player
         ON Actions.PlayerId = Player.PlayerId
'''

cursor.execute(query)
cursor.fetchall()

(('Nicolas Batum', 7),
 ('LaMarcus Aldridge', 6),
 ('Robin Lopez', 1),
 ('Wesley Matthews', 6),
 ('Damian Lillard', 8),
 ('Thomas Robinson', 0),
 ('Maurice Williams', 3),
 ('Will Barton', 1),
 ('Dorell Wright', 0),
 ('Earl Watson', 0),
 ('CJ McCollum', 0),
 ('Meyers Leonard', 0),
 ('Victor Claver', 0),
 ('Kent Bazemore', 1),
 ('Kent Bazemore', 6),
 ('Pau Gasol', 7),
 ('Pau Gasol', 0),
 ('Chris Kaman', 2),
 ('Chris Kaman', 0),
 ('Jodie Meeks', 2),
 ('Jodie Meeks', 1),
 ('Kendall Marshall', 5),
 ('Kendall Marshall', 10),
 ('Steve Nash', 10),
 ('Steve Nash', 0),
 ('Xavier Henry', 0),
 ('Xavier Henry', 0),
 ('Robert Sacre', 1),
 ('Robert Sacre', 3),
 ('Ryan Kelly', 2),
 ('Ryan Kelly', 2),
 ('Nick Young', 1),
 ('Nick Young', 1),
 ('Marshon Brooks', 0),
 ('Marshon Brooks', 0),
 ('Jordan Hill', 0),
 ('Jordan Hill', 0),
 ('Wesley Johnson', 0),
 ('Wesley Johnson', 3),
 ('Andre Iguodala', 7),
 ('Andre Iguodala', 0),
 ('Draymond Green', 6),
 ('Draymond Green', 4),
 ("Jermaine O'Neal", 0),
 ("Jermaine O'Neal", 0),
 ('Klay Thompson', 5),
 ('Klay Thompson', 2),
 ('Stephen Curry', 5),
 ('Stephen Curry', 10),
 ('Marreese Speights', 1),
 ('Marreese Speights', 0),
 ('Harrison Barnes', 1),
 ('Harrison Barnes', 0),
 ('Steve Blake', 3),
 ('Steve Blake', 3),
 ('Jordan Crawford', 0),
 ('Jordan Crawford', 2),
 ('Hilton Armstrong', 0),
 ('Hilton Armstrong', 2),
 ('Andrew Bogut', 0),
 ('Andrew Bogut', 0),
 ('David Lee', 0),
 ('Shawn Marion', 2),
 ('Shawn Marion', 2),
 ('Dirk Nowitzki', 3),
 ('Dirk Nowitzki', 1),
 ('Samuel Dalembert', 0),
 ('Samuel Dalembert', 1),
 ('Monta Ellis', 6),
 ('Monta Ellis', 9),
 ('Jose Calderon', 6),
 ('Jose Calderon', 1),
 ('Vince Carter', 4),
 ('Vince Carter', 1),
 ('Brandan Wright', 0),
 ('Brandan Wright', 1),
 ('Devin Harris', 4),
 ('Devin Harris', 7),
 ('Jae Crowder', 2),
 ('Jae Crowder', 1),
 ('DeJuan Blair', 0),
 ('DeJuan Blair', 0),
 ('Wayne Ellington', 0),
 ('Wayne Ellington', 0),
 ('Bernard James', 0),
 ('Bernard James', 0),
 ('Shane Larkin', 0),
 ('Shane Larkin', 0),
 ('Chandler Parsons', 4),
 ('Chandler Parsons', 3),
 ('Donatas Motiejunas', 0),
 ('Donatas Motiejunas', 1),
 ('Omer Asik', 0),
 ('Omer Asik', 0),
 ('James Harden', 0),
 ('James Harden', 4),
 ('Jeremy Lin', 2),
 ('Jeremy Lin', 7),
 ('Omri Casspi', 0),
 ('Omri Casspi', 1),
 ('Francisco Garcia', 3),
 ('Francisco Garcia', 2),
 ('Isaiah Canaan', 1),
 ('Isaiah Canaan', 1),
 ('Jordan Hamilton', 3),
 ('Jordan Hamilton', 0),
 ('Patrick Beverley', 0),
 ('Patrick Beverley', 0),
 ('Dwight Howard', 0),
 ('Dwight Howard', 0),
 ('Terrence Jones', 0),
 ('Terrence Jones', 0),
 ('Greg Smith', 0),
 ('Greg Smith', 0),
 ('Joe Johnson', 3),
 ('Joe Johnson', 1),
 ('Paul Pierce', 1),
 ('Paul Pierce', 1),
 ('Mason Plumlee', 4),
 ('Mason Plumlee', 2),
 ('Shaun Livingston', 2),
 ('Shaun Livingston', 3),
 ('Deron Williams', 6),
 ('Deron Williams', 0),
 ('Alan Anderson', 2),
 ('Alan Anderson', 0),
 ('Andray Blatche', 2),
 ('Andray Blatche', 1),
 ('Mizra Teletovic', 1),
 ('Mizra Teletovic', 1),
 ('Jorge Gutierrez', 2),
 ('Jorge Gutierrez', 0),
 ('Marquis Teague', 0),
 ('Marquis Teague', 2),
 ('Jason Collins', 0),
 ('Jason Collins', 0),
 ('Andrei Kirilenko', 0),
 ('Andrei Kirilenko', 0),
 ('Marcus Thornton', 0),
 ('Marcus Thornton', 0),
 ('JR Smith', 4),
 ('JR Smith', 6),
 ('Carmelo Anthony', 3),
 ('Carmelo Anthony', 3),
 ('Tyson Chandler', 1),
 ('Tyson Chandler', 1),
 ('Iman Shumpert', 0),
 ('Iman Shumpert', 2),
 ('Raymond Felton', 6),
 ('Raymond Felton', 3),
 ('Timothy Hardaway Jr.', 2),
 ('Timothy Hardaway Jr.', 0),
 ('Pablo Prigioni', 2),
 ('Pablo Prigioni', 3),
 ('Cole Aldrich', 0),
 ('Cole Aldrich', 0),
 ('Jeremy Tyler', 0),
 ('Jeremy Tyler', 0),
 ('Shannon Brown', 0),
 ('Shannon Brown', 0),
 ('Toure Murry', 0),
 ('Toure Murry', 1),
 ("Amar'e Stoudemire", 0),
 ("Amar'e Stoudemire", 2),
 ('Richard Jefferson', 3),
 ('Marvin Williams', 2),
 ('Derrick Favors', 0),
 ('Gordon Hayward', 1),
 ('Trey Burke', 3),
 ('Enes Kanter', 0),
 ('Alec Burks', 4),
 ('Diante Garrett', 1),
 ('Ian Clark', 1),
 ('Rudy Gobert', 0),
 ('Jeremy Evans', 0),
 ('John Lucas III', 0),
 ('Brandon Rush', 0),
 ('Tayshaun Prince', 1),
 ('Tayshaun Prince', 0),
 ('Tayshaun Prince', 1),
 ('Zach Randolph', 3),
 ('Zach Randolph', 3),
 ('Zach Randolph', 4),
 ('Marc Gasol', 2),
 ('Marc Gasol', 4),
 ('Marc Gasol', 3),
 ('Courtney Lee', 3),
 ('Courtney Lee', 0),
 ('Courtney Lee', 1),
 ('Mike Conley', 2),
 ('Mike Conley', 8),
 ('Mike Conley', 4),
 ('Nick Calathes', 3),
 ('Nick Calathes', 3),
 ('Nick Calathes', 2),
 ('Ed Davis', 1),
 ('Ed Davis', 0),
 ('Ed Davis', 0),
 ('Mike Miller', 0),
 ('Mike Miller', 3),
 ('Mike Miller', 2),
 ('Kosta Koufos', 0),
 ('Kosta Koufos', 0),
 ('Kosta Koufos', 0),
 ('Tony Allen', 2),
 ('Tony Allen', 1),
 ('Tony Allen', 1),
 ('James Johnson', 0),
 ('James Johnson', 2),
 ('James Johnson', 0),
 ('Jon Leuer', 0),
 ('Jon Leuer', 0),
 ('Jon Leuer', 0),
 ('Beno Udrih', 0),
 ('Beno Udrih', 0),
 ('Beno Udrih', 0),
 ('Quincy Miller', 0),
 ('Quincy Miller', 0),
 ('Quincy Miller', 0),
 ('Kenneth Faried', 2),
 ('Kenneth Faried', 2),
 ('Kenneth Faried', 2),
 ('Timofey Mozgov', 1),
 ('Timofey Mozgov', 0),
 ('Timofey Mozgov', 2),
 ('Randy Foye', 4),
 ('Randy Foye', 7),
 ('Randy Foye', 4),
 ('Ty Lawson', 6),
 ('Ty Lawson', 12),
 ('Ty Lawson', 3),
 ('Darrell Arthur', 0),
 ('Darrell Arthur', 0),
 ('Darrell Arthur', 1),
 ('Evan Fournier', 1),
 ('Evan Fournier', 7),
 ('Evan Fournier', 0),
 ('Aaron Brooks', 6),
 ('Aaron Brooks', 1),
 ('Aaron Brooks', 2),
 ('Jan Vesely', 0),
 ('Jan Vesely', 2),
 ('Jan Vesely', 2),
 ('Wilson Chandler', 0),
 ('Wilson Chandler', 0),
 ('Wilson Chandler', 0),
 ('JJ Hickson', 0),
 ('JJ Hickson', 0),
 ('JJ Hickson', 0),
 ('Anthony Randolph', 0),
 ('Anthony Randolph', 3),
 ('Anthony Randolph', 0),
 ('Nate Robinson', 0),
 ('Nate Robinson', 0),
 ('Nate Robinson', 0),
 ('Rudy Gay', 5),
 ('Rudy Gay', 4),
 ('Reggie Evans', 0),
 ('Reggie Evans', 0),
 ('DeMarcus Cousins', 3),
 ('DeMarcus Cousins', 2),
 ('Ben McLemore', 1),
 ('Ben McLemore', 0),
 ('Ray McCallum', 10),
 ('Ray McCallum', 5),
 ('Travis Outlaw', 1),
 ('Travis Outlaw', 2),
 ('Derrick Williams', 0),
 ('Derrick Williams', 0),
 ('Jared Cunningham', 0),
 ('Jared Cunningham', 0),
 ('Jason Thompson', 0),
 ('Jason Thompson', 3),
 ('Quincy Acy', 0),
 ('Quincy Acy', 0),
 ('Aaron Gray', 0),
 ('Aaron Gray', 0),
 ('Isaiah Thomas', 0),
 ('Isaiah Thomas', 0),
 ('Al-Farouq Aminu', 0),
 ('Al-Farouq Aminu', 1),
 ('Anthony Davis', 4),
 ('Anthony Davis', 1),
 ('Greg Stiemsma', 0),
 ('Greg Stiemsma', 1),
 ('Tyreke Evans', 4),
 ('Tyreke Evans', 3),
 ('Brian Roberts', 2),
 ('Brian Roberts', 6),
 ('Darius Miller', 1),
 ('Darius Miller', 1),
 ('Alexis Ajinca', 0),
 ('Alexis Ajinca', 2),
 ('Austin Rivers', 9),
 ('Austin Rivers', 2),
 ('Anthony Morrow', 1),
 ('Anthony Morrow', 2),
 ('Jeff Withey', 1),
 ('Jeff Withey', 1),
 ('Luke Babbitt', 0),
 ('Luke Babbitt', 1),
 ('Eric Gordon', 0),
 ('Eric Gordon', 0),
 ('Jason Smith', 0),
 ('Jason Smith', 0),
 ('Matt Barnes', 3),
 ('Matt Barnes', 1),
 ('Matt Barnes', 2),
 ('Jared Dudley', 3),
 ('Jared Dudley', 0),
 ('Jared Dudley', 2),
 ('DeAndre Jordan', 0),
 ('DeAndre Jordan', 0),
 ('DeAndre Jordan', 0),
 ('Darren Collison', 7),
 ('Darren Collison', 5),
 ('Darren Collison', 1),
 ('Chris Paul', 9),
 ('Chris Paul', 9),
 ('Chris Paul', 9),
 ('Hidayet Turkoglu', 0),
 ('Willie Green', 1),
 ('Willie Green', 0),
 ('Willie Green', 0),
 ('Reggie Bullock', 0),
 ('Reggie Bullock', 0),
 ('Reggie Bullock', 0),
 ('Ryan Hollins', 0),
 ('Ryan Hollins', 0),
 ('Ryan Hollins', 0),
 ('Glen Davis', 0),
 ('Glen Davis', 0),
 ('Glen Davis', 0),
 ('Jamal Crawford', 0),
 ('Jamal Crawford', 0),
 ('Jamal Crawford', 0),
 ('Danny Granger', 0),
 ('Danny Granger', 0),
 ('Blake Griffin', 0),
 ('Blake Griffin', 3),
 ('Blake Griffin', 11),
 ('Corey Brewer', 1),
 ('Corey Brewer', 2),
 ('Kevin Love', 4),
 ('Kevin Love', 10),
 ('Hidayet Turkoglu', 0),
 ('Hidayet Turkoglu', 0),
 ('Kevin Martin', 0),
 ('Kevin Martin', 2),
 ('Ricky Rubio', 7),
 ('Ricky Rubio', 7),
 ('Gorgui Dieng', 3),
 ('Gorgui Dieng', 0),
 ('Jose Barea', 8),
 ('Jose Barea', 7),
 ('Dante Cunningham', 2),
 ('Dante Cunningham', 1),
 ('Chase Budinger', 1),
 ('Chase Budinger', 0),
 ('Robbie Hummel', 3),
 ('Robbie Hummel', 0),
 ('Shabazz Muhammad', 1),
 ('Shabazz Muhammad', 0),
 ('Luc Mbah a Moute', 0),
 ('Luc Mbah a Moute', 0),
 ('Alexey Shved', 0),
 ('Alexey Shved', 0),
 ('Jeff Green', 1),
 ('Jeff Green', 3),
 ('Brandon Bass', 3),
 ('Brandon Bass', 0),
 ('Kris Humphries', 1),
 ('Kris Humphries', 0),
 ('Avery Bradley', 3),
 ('Avery Bradley', 0),
 ('Jerryd Bayless', 5),
 ('Jerryd Bayless', 1),
 ('Jared Sullinger', 1),
 ('Jared Sullinger', 1),
 ('Christapher Johnson', 0),
 ('Christapher Johnson', 1),
 ('Phil Pressey', 3),
 ('Phil Pressey', 6),
 ('Kelly Olynyk', 0),
 ('Kelly Olynyk', 1),
 ('Chris Babb', 0),
 ('Chris Babb', 1),
 ('Joel Anthony', 0),
 ('Joel Anthony', 0),
 ('Rajon Rondo', 0),
 ('Rajon Rondo', 6),
 ('Mike Dunleavy', 3),
 ('Mike Dunleavy', 3),
 ('Carlos Boozer', 1),
 ('Carlos Boozer', 2),
 ('Joakim Noah', 5),
 ('Joakim Noah', 6),
 ('Jimmy Butler', 4),
 ('Jimmy Butler', 2),
 ('Kirk Hinrich', 3),
 ('Kirk Hinrich', 6),
 ('DJ Augustin', 11),
 ('DJ Augustin', 5),
 ('Taj Gibson', 0),
 ('Taj Gibson', 2),
 ('Nazr Mohammed', 0),
 ('Nazr Mohammed', 0),
 ('Tony Snell', 1),
 ('Tony Snell', 1),
 ('Jimmer Fredette', 0),
 ('Jimmer Fredette', 0),
 ('Erik Murphy', 0),
 ('Erik Murphy', 0),
 ('Tornike Shengelia', 0),
 ('Tornike Shengelia', 0),
 ('Terrence Ross', 0),
 ('Terrence Ross', 0),
 ('Terrence Ross', 1),
 ('Amir Johnson', 1),
 ('Amir Johnson', 0),
 ('Jonas Valanciunas', 0),
 ('Jonas Valanciunas', 1),
 ('Jonas Valanciunas', 0),
 ('Demar DeRozan', 7),
 ('Demar DeRozan', 4),
 ('Demar DeRozan', 9),
 ('Kyle Lowry', 4),
 ('Patrick Patterson', 0),
 ('Patrick Patterson', 1),
 ('Patrick Patterson', 2),
 ('Steve Novak', 0),
 ('Steve Novak', 0),
 ('Steve Novak', 0),
 ('John Salmons', 3),
 ('John Salmons', 2),
 ('John Salmons', 1),
 ('Greivis Vasquez', 1),
 ('Greivis Vasquez', 8),
 ('Greivis Vasquez', 3),
 ('Chuck Hayes', 0),
 ('Chuck Hayes', 0),
 ('Chuck Hayes', 2),
 ('Nando De Colo', 1),
 ('Nando De Colo', 2),
 ('Nando De Colo', 5),
 ('Landry Fields', 0),
 ('Landry Fields', 0),
 ('Landry Fields', 0),
 ('Tyler Hansbrough', 0),
 ('Tyler Hansbrough', 2),
 ('Tyler Hansbrough', 0),
 ('Lebron James', 8),
 ('Lebron James', 8),
 ('Udonis Haslem', 1),
 ('Udonis Haslem', 0),
 ('Chris Bosh', 2),
 ('Chris Bosh', 2),
 ('Toney Douglas', 0),
 ('Toney Douglas', 3),
 ('Mario Chalmers', 4),
 ('Mario Chalmers', 3),
 ('Rashad Lewis', 2),
 ('Rashad Lewis', 2),
 ('Norris Cole', 2),
 ('Norris Cole', 3),
 ('James Jones', 0),
 ('James Jones', 0),
 ('Chris Andersen', 0),
 ('Chris Andersen', 0),
 ('Shane Battier', 0),
 ('Shane Battier', 0),
 ('Michael Beasley', 0),
 ('Michael Beasley', 1),
 ('Justin Hamilton', 0),
 ('Justin Hamilton', 0),
 ('Dwayne Wade', 0),
 ('Khris Middleton', 1),
 ('Khris Middleton', 2),
 ('Jeff Adrien', 1),
 ('Jeff Adrien', 2),
 ('Zaza Pachulia', 6),
 ('Zaza Pachulia', 4),
 ('Ramon Sessions', 11),
 ('Ramon Sessions', 6),
 ('Brandon Knight', 7),
 ('Brandon Knight', 2),
 ('Giannis Antetokounmpo', 2),
 ('Giannis Antetokounmpo', 1),
 ('John Henson', 0),
 ('John Henson', 0),
 ('Ekpe Udoh', 0),
 ('Ekpe Udoh', 1),
 ('Ersan Ilyasova', 0),
 ('Ersan Ilyasova', 0),
 ('OJ Mayo', 0),
 ('OJ Mayo', 0),
 ('Miroslav Raduljica', 0),
 ('Miroslav Raduljica', 0),
 ('DJ Stephens', 0),
 ('DJ Stephens', 0),
 ('Nate Wolters', 0),
 ('Nate Wolters', 0),
 ('Josh Smith', 3),
 ('Josh Smith', 1),
 ('Greg Monroe', 1),
 ('Greg Monroe', 2),
 ('Andre Drummond', 0),
 ('Andre Drummond', 0),
 ('Kyle Singler', 2),
 ('Kyle Singler', 3),
 ('Brandon Jennings', 13),
 ('Brandon Jennings', 9),
 ('Rodney Stuckey', 0),
 ('Rodney Stuckey', 0),
 ('Jonas Jerebko', 1),
 ('Jonas Jerebko', 0),
 ('Kentavious Caldwell-Pope', 0),
 ('Kentavious Caldwell-Pope', 1),
 ('Will Bynum', 8),
 ('Will Bynum', 0),
 ('Charlie Villanueva', 0),
 ('Charlie Villanueva', 0),
 ('Luigi Datome', 0),
 ('Luigi Datome', 0),
 ('Tony Mitchell', 0),
 ('Tony Mitchell', 0),
 ('Peyton Siva', 0),
 ('Peyton Siva', 0),
 ('Hollis Thompson', 2),
 ('Hollis Thompson', 0),
 ('Thaddeus Young', 4),
 ('Thaddeus Young', 4),
 ('Henry Sims', 2),
 ('Henry Sims', 2),
 ('James Anderson', 4),
 ('James Anderson', 2),
 ('Michael Carter-Williams', 9),
 ('Michael Carter-Williams', 3),
 ('Tony Wroten', 3),
 ('Tony Wroten', 4),
 ('Jarvis Varnado', 0),
 ('Jarvis Varnado', 4),
 ('Elliot Williams', 1),
 ('Elliot Williams', 0),
 ('Casper Ware', 0),
 ('Casper Ware', 1),
 ('Brandon Davies', 0),
 ('Brandon Davies', 0),
 ('Arnett Moultrie', 0),
 ('Arnett Moultrie', 0),
 ('James Nunnally', 0),
 ('James Nunnally', 1),
 ('DeMarre Carroll', 4),
 ('DeMarre Carroll', 3),
 ('Paul Millsap', 4),
 ('Paul Millsap', 3),
 ('Pero Antic', 2),
 ('Pero Antic', 1),
 ('Kyle Korver', 2),
 ('Kyle Korver', 1),
 ('Jeff Teague', 5),
 ('Jeff Teague', 8),
 ('Louis Williams', 5),
 ('Louis Williams', 5),
 ('Elton Brand', 1),
 ('Elton Brand', 3),
 ('Mike Scott', 0),
 ('Mike Scott', 0),
 ('Dennis Schroder', 2),
 ('Dennis Schroder', 0),
 ('Mike Muscala', 0),
 ('Mike Muscala', 0),
 ('Shelvin Mack', 0),
 ('Shelvin Mack', 0),
 ('Cartier Martin', 0),
 ('Cartier Martin', 0),
 ('Trevor Ariza', 1),
 ('Trevor Ariza', 0),
 ('Trevor Booker', 1),
 ('Trevor Booker', 1),
 ('Marcin Gortat', 1),
 ('Marcin Gortat', 4),
 ('Bradley Beal', 5),
 ('Bradley Beal', 2),
 ('John Wall', 6),
 ('John Wall', 10),
 ('Drew Gooden', 2),
 ('Drew Gooden', 1),
 ('Martell Webster', 1),
 ('Martell Webster', 2),
 ('Al Harrington', 0),
 ('Al Harrington', 1),
 ('Andre Miller', 9),
 ('Andre Miller', 8),
 ('Kevin Seraphin', 0),
 ('Kevin Seraphin', 0),
 ('Otto Porter', 0),
 ('Otto Porter', 0),
 ('Chris Singleton', 0),
 ('Chris Singleton', 0),
 ('Garrett Temple', 0),
 ('Garrett Temple', 0),
 ('Michael Kidd-Gilchrist', 0),
 ('Michael Kidd-Gilchrist', 2),
 ('Michael Kidd-Gilchrist', 1),
 ('Josh McRoberts', 1),
 ('Josh McRoberts', 0),
 ('Josh McRoberts', 0),
 ('Al Jefferson', 0),
 ('Al Jefferson', 0),
 ('Al Jefferson', 0),
 ('Gerald Henderson', 2),
 ('Gerald Henderson', 4),
 ('Gerald Henderson', 2),
 ('Kemba Walker', 10),
 ('Kemba Walker', 5),
 ('Kemba Walker', 10),
 ('Cody Zeller', 2),
 ('Cody Zeller', 3),
 ('Cody Zeller', 0),
 ('Bismack Biyombo', 0),
 ('Bismack Biyombo', 0),
 ('Bismack Biyombo', 1),
 ('Gary Neal', 1),
 ('Gary Neal', 3),
 ('Gary Neal', 2),
 ('Luke Ridnour', 1),
 ('Luke Ridnour', 1),
 ('Luke Ridnour', 1),
 ('Chris Douglas-Roberts', 0),
 ('Chris Douglas-Roberts', 4),
 ('Chris Douglas-Roberts', 3),
 ('Jannero Pargo', 0),
 ('Jannero Pargo', 5),
 ('Jannero Pargo', 0),
 ('Anthony Tolliver', 0),
 ('Anthony Tolliver', 5),
 ('Anthony Tolliver', 1),
 ('DJ White', 0),
 ('DJ White', 0),
 ('DJ White', 0),
 ('Paul George', 7),
 ('Paul George', 3),
 ('David West', 3),
 ('David West', 4),
 ('Roy Hibbert', 3),
 ('Roy Hibbert', 0),
 ('Lance Stephenson', 4),
 ('Lance Stephenson', 1),
 ('George Hill', 2),
 ('George Hill', 5),
 ('Luis Scola', 2),
 ('Luis Scola', 1),
 ('Evan Turner', 1),
 ('Evan Turner', 1),
 ('Ian Mahinmi', 1),
 ('Ian Mahinmi', 0),
 ('Rasual Butler', 0),
 ('Rasual Butler', 1),
 ('Donald Sloan', 1),
 ('Donald Sloan', 3),
 ('Lavoy Allen', 0),
 ('Lavoy Allen', 0),
 ('Chris Copeland', 0),
 ('Chris Copeland', 0),
 ('Solomon Hill', 0),
 ('Solomon Hill', 0),
 ('Luol Deng', 2),
 ('Tristan Thompson', 0),
 ('Spencer Hawes', 5),
 ('Dion Waiters', 3),
 ('Kyrie Irving', 8),
 ('Jarrett Jack', 4),
 ('Matthew Dellavedova', 5),
 ('Tyler Zeller', 0),
 ('Alonzo Gee', 0),
 ('Sergey Karasev', 1),
 ('Scotty Hopson', 0),
 ('Anderson Varejao', 0),
 ('Maurice Harkless', 0),
 ('Maurice Harkless', 1),
 ("Kyle O'Quinn", 2),
 ("Kyle O'Quinn", 1),
 ('Nikola Vucevic', 2),
 ('Nikola Vucevic', 0),
 ('Arron Afflalo', 5),
 ('Arron Afflalo', 0),
 ('Jameer Nelson', 4),
 ('Jameer Nelson', 7),
 ('Andrew Nicholson', 1),
 ('Andrew Nicholson', 0),
 ('Victor Oladipo', 4),
 ('Victor Oladipo', 2),
 ('Etwaun Moore', 0),
 ('Etwaun Moore', 2),
 ('Tobias Harris', 1),
 ('Tobias Harris', 1),
 ('Doron Lamb', 1),
 ('Doron Lamb', 1),
 ('Dewayne Dedmon', 1),
 ('Dewayne Dedmon', 0),
 ('Jason Maxiell', 0),
 ('Jason Maxiell', 0),
 ('Ronnie Price', 0),
 ('Ronnie Price', 0),
 ('Julyan Stone', 0),
 ('Julyan Stone', 0),
 ('Ray Allen', 0),
 ('Ronny Turiaf', 2),
 ('Kawhi Leonard', 1),
 ('Kawhi Leonard', 3),
 ('Tim Duncan', 0),
 ('Tim Duncan', 1),
 ('Boris Diaw', 5),
 ('Boris Diaw', 2),
 ('Daniel Green', 2),
 ('Daniel Green', 2),
 ('Tony Parker', 8),
 ('Tony Parker', 3),
 ('Emanuel Ginobli', 5),
 ('Emanuel Ginobli', 0),
 ('Tiago Splitter', 2),
 ('Tiago Splitter', 2),
 ('Patrick Mills', 2),
 ('Patrick Mills', 1),
 ('Marco Belinelli', 1),
 ('Marco Belinelli', 1),
 ('Jeff Ayres', 2),
 ('Jeff Ayres', 2),
 ('Cory Joseph', 1),
 ('Cory Joseph', 1),
 ('Aron Baynes', 0),
 ('Austin Daye', 0),
 ('Austin Daye', 0),
 ('PJ Tucker', 1),
 ('Channing Frye', 1),
 ('Miles Plumlee', 1),
 ('Goran Dragic', 8),
 ('Eric Bledsoe', 3),
 ('Gerald Green', 0),
 ('Markieff Morris', 2),
 ('Marcus Morris', 1),
 ('Ish Smith', 0),
 ('Dionte Christmas', 0),
 ('Archie Goodwin', 0),
 ('Alex Len', 0),
 ('Shavlik Randolph', 0),
 ('Orlando Johnson', 0),
 ('Royce White', 0),
 ('Damion James', 0),
 ('Kevin Durant', 3),
 ('Serge Ibaka', 0),
 ('Kendrick Perkins', 1),
 ('Andre Roberson', 0),
 ('Russell Westbrook', 6),
 ('Caron Butler', 2),
 ('Steven Adams', 0),
 ('Nick Collison', 2),
 ('Reggie Jackson', 4),
 ('Derek Fisher', 0),
 ('Jeremy Lamb', 0),
 ('Perry Jones', 0),
 ('Hasheem Thabeet', 0),
 ('JJ Redick', 1),
 ('Dwight Buycks', 0),
 ('David Lee', 0),
 ('Nikola Pekovic', 0))

In [44]:
query = '''SELECT  PlayerName,Assists
         FROM Actions
         JOIN Player
         ON Actions.PlayerId = Player.PlayerId
         WHERE Assists > 5
'''

pd.read_sql(query,db)

/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

        PlayerName  Assists
0   Raymond Felton        6
1        Ty Lawson        6
2     Aaron Brooks        6
3     Ray McCallum       10
4    Austin Rivers        9
..             ...      ...
64      Chris Paul        9
65   Blake Griffin       11
66    Kemba Walker       10
67   Jameer Nelson        7
68   Demar DeRozan        9

[69 rows x 2 columns]

Obtenemos el TOP 10 jugadores con más asistencias en la temporada

In [49]:
query = ''' SELECT PlayerName, SUM(Assists) AS TotalAssists

            FROM Actions
            JOIN Player
            ON Actions.PlayerId = Player.PlayerId
            GROUP BY PlayerName
            ORDER BY TotalAssists DESC
            LIMIT 10
    
'''

Asistencias = pd.read_sql(query, db)
Asistencias

/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

         PlayerName  TotalAssists
0        Chris Paul          27.0
1      Kemba Walker          25.0
2  Brandon Jennings          22.0
3         Ty Lawson          21.0
4     Demar DeRozan          20.0
5    Ramon Sessions          17.0
6      Andre Miller          17.0
7       DJ Augustin          16.0
8         John Wall          16.0
9      Lebron James          16.0

Obtenemos el TOP 10 Equipos con más puntuación media por partido

In [66]:
# sumas los puntos de todos los jugadores de un equipo por partido,
# haces la media de puntos de todos los jugadores de un equipo en todos los partidos
# comparas con la media de otros equipo

query =''' 
    SELECT TeamName, AVG(PointsMatch) as AvgPoints

    FROM (

          SELECT TeamName, GameId, SUM(Points) as PointsMatch

          FROM Actions
          JOIN Team
          ON Actions.TeamId = Team.TeamId
          GROUP BY TeamName,GameId
       ) TABLA

    GROUP BY TeamName
    ORDER BY AvgPoints DESC
    LIMIT 10

'''

pd.read_sql(query, db)

                 TeamName  AvgPoints
0  Portland Trail Blazers   124.0000
1     Cleveland Cavaliers   119.0000
2        Dallas Mavericks   116.5000
3   Golden State Warriors   112.5000
4    Los Angeles Clippers   111.0000
5       Charlotte Bobcats   108.3333
6            Phoenix Suns   108.0000
7          Denver Nuggets   107.0000
8      Los Angeles Lakers   107.0000
9   Oklahoma City Thunder   106.0000